### ISSUE TITLE
GitLab: Failed to start nginx

### ISSUE THREAD

**Issue by joh-klein** [jirutka/nginx-testing#1]
Hi,
first, let me thank you (a lot) for your multiple tools that helped me in my njs development! Really nice and thorough.

Now, my issue is, I can't get the tests to run in my CI environment. Do you have any ideas how I could debug this?
The container that the gitlab runner is using is "node:14.16.1" – which, afaik, should have everything needed …

Thanks again and maybe you have an idea how I could get it to run.

**Comment by jirutka** [comment]
Hi, thanks for the kind words!

It’s really impossible to say where’s the problem without any log… Enable debug logging and paste the log here.

**Comment by joh-klein** [comment]
Thanks for your answer. I tried debug logging with `DEBUG=nginx-binaries` – but I can't see anything out of the ordinary …

```
[…]

2021-04-30T13:13:27.813Z nginx-binaries Fetching https://jirutka.github.io/nginx-binaries/index.json
2021-04-30T13:13:28.014Z nginx-binaries Looking for nginx binary matching {arch: x86_64, os: linux, variant: , version: 1.18.x}
  console.info
    nginx-binaries: Downloading https://jirutka.github.io/nginx-binaries/nginx-1.18.0-x86_64-linux...
      at Object.<anonymous>.exports.log.<computed> [as info] (node_modules/nginx-binaries/src/logger.ts:39:52)
2021-04-30T13:13:28.379Z nginx-binaries File was saved in /builds/[folder]/[repo]/node_modules/.cache/nginx-binaries/nginx-1.18.0-x86_64-linux
  console.info
    nginx-testing: Starting nginx 1.18.0 on port(s): 34129
      at Object.<anonymous>.exports.log.<computed> [as info] (node_modules/nginx-testing/src/logger.ts:41:52)

[…]

    Failed to start nginx, no response on port 34129
      at startAndCheckNginxProcess (node_modules/nginx-testing/src/nginxRunner.ts:519:11)
      at Object.startNginx (node_modules/nginx-testing/src/nginxRunner.ts:338:40)

[…]

    nginx-testing: 2021/04/30 13:13:28 [emerg] 186#186: getpwnam("nginx") failed
      at Object.<anonymous>.exports.log.<computed> [as error] (node_modules/nginx-testing/src/logger.ts:41:52)
      at dumpErrorLog (node_modules/nginx-testing/src/nginxRunner.ts:503:16)
      at startAndCheckNginxProcess (node_modules/nginx-testing/src/nginxRunner.ts:518:5)
      at Object.startNginx (node_modules/nginx-testing/src/nginxRunner.ts:338:40)
```

**Comment by jirutka** [comment]
Hmm, nginx fails to start because there’s no system user `nginx`. I haven’t encountered this problem yet because I currently run tests even against the system-provided nginx, so I have the `nginx` user present on the system. nginx-testing doesn’t start nginx as `nginx` user, but it seems that it’s still checking its existence for some reason.

This is a major bug I have to fix. I’ll try to look at it this weekend.

If you need a quick workaround now, just create user `nginx` before running tests.

**Comment by jirutka** [comment]
I assume that you don’t explicitly set `user nginx;` in your nginx.conf…?

**Comment by joh-klein** [comment]
No, I am not – but I am trying it right now.

I just realized, that that was even more wrong :) I evidently didn't fully comprehend your earlier comment 🤦

**Comment by joh-klein** [comment]
You were correct. I added the line `adduser --disabled-password --gecos "" nginx` to my gitlab-ci.yml and the tests ran perfectly fine.

**Comment by joh-klein** [comment]
Thanks for the quick fix!
I am sorry to tell you, though, that it didn't really fix it for me – now I get:

```
nginx-testing: 2021/05/03 10:37:13 [emerg] 207#207: getgrnam("nobody") failed
      at Object.<anonymous>.exports.log.<computed> [as error] (node_modules/nginx-testing/src/logger.ts:41:52)
      at dumpErrorLog (node_modules/nginx-testing/src/nginxRunner.ts:503:16)
      at startAndCheckNginxProcess (node_modules/nginx-testing/src/nginxRunner.ts:518:5)
      at Object.startNginx (node_modules/nginx-testing/src/nginxRunner.ts:338:40)
```

**Comment by jirutka** [comment]
How’s that possible that you don’t have user `nobody`? o.O What’s in your `/etc/passwd`?

**Comment by joh-klein** [comment]
To be exact, the error states, that there is no group called "nobody" …

I am using a docker container (in this case `node:14.16.1`) to build my app, so this is the output from inside this container:


```
$ cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
_apt:x:100:65534::/nonexistent:/bin/false
node:x:1000:1000::/home/node:/bin/bash
```

```
$ cat /etc/group
root:x:0:
daemon:x:1:
bin:x:2:
sys:x:3:
adm:x:4:
tty:x:5:
disk:x:6:
lp:x:7:
mail:x:8:
news:x:9:
uucp:x:10:
man:x:12:
proxy:x:13:
kmem:x:15:
dialout:x:20:
fax:x:21:
voice:x:22:
cdrom:x:24:
floppy:x:25:
tape:x:26:
sudo:x:27:
audio:x:29:
dip:x:30:
www-data:x:33:
backup:x:34:
operator:x:37:
list:x:38:
irc:x:39:
src:x:40:
gnats:x:41:
shadow:x:42:
utmp:x:43:
video:x:44:
sasl:x:45:
plugdev:x:46:
staff:x:50:
games:x:60:
users:x:100:
nogroup:x:65534:
ssh:x:101:
node:x:1000:
```

```
$ groups nobody
nobody : nogroup
```

**Comment by jirutka** [comment]
I’ve changed the default group to `nogroup`, which seems to be more widespread.
